###############################################################################
# Even Fibonacci numbers
#
# https://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
###############################################################################

import unittest
from .problem0002 import problem0002


class TestProblem0002(unittest.TestCase):

    def test_problem0002(self):

        _expected_found = 4613732
        _input_top = 4000000

        self.assertEqual(problem0002(_input_top), _expected_found)
