###############################################################################
# Even Fibonacci numbers
#
# https://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million,
# find the sum of the even-valued terms.
###############################################################################

import logging

LOGGER = logging.getLogger(__name__)


def problem0002(_top):
    i = 0
    last1 = 1
    last2 = 0
    even_sum = 0

    fibo = 0

    while fibo < _top:
        fibo = last2 + last1

        LOGGER.debug("Fibonacci(%d) = %d", i, fibo)

        if 0 == fibo % 2:
            even_sum += fibo

        # next keys:
        last2 = last1
        last1 = fibo
        i += 1

    LOGGER.info('Problem 0002 result: %i', even_sum)

    return even_sum
