---
name: Python CI Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: ['main']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['main']
  workflow_dispatch:

jobs:
  lint:
    name: 'Python CI Lint'
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'macos-14', 'windows-2022']
        python: ['3.12', '3.13', '3.14']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}

      - name: Install tooling on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pipenv
        shell: bash

      - name: Install tooling on macOS
        if: runner.os == 'macOS'
        run: |
          brew install pipenv
        shell: bash

      - name: Install tooling on Windows
        if: runner.os == 'Windows'
        run: |
          python -m pip install --user pipenv==2026.6.1
        shell: pwsh

      - name: Tooling check
        run: |
          python3 --version
          pipenv --version
          make --version

      - name: Install
        run: |
          # Use the lockfile to install deterministic, audited dependencies
          pipenv sync --dev

      - name: Lint (pylint)
        run: |
          pipenv run pylint --verbose --recursive yes src/

      - name: Lint (flake8)
        run: |
          pipenv run flake8 --verbose src/

      - name: Lint (pyright) static type checker
        run: |
          pipenv run pyright --verbose src/

      - name: Styling (pycodestyle)
        run: |
          pipenv run pycodestyle --statistics src/

      - name: Styling (autopep8)
        run: |
          pipenv run autopep8  --diff --recursive --exit-code --verbose .
