---
name: Python CI Test

on: # yamllint disable-line rule:truthy
  push:
    branches: ['main']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['main']
  workflow_dispatch:

env:
  LOG_LEVEL: INFO

jobs:
  test:
    name: 'Python CI Test'
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'macos-14', 'windows-2022']
        python: ['3.12', '3.13', '3.14']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}

      - name: Install
        run: |
          pip3 install -r requirements.txt

      - name: Test
        run: >
          coverage run -m pytest --verbose
          -o log_cli=true
          --log-cli-level=INFO
          src/

      - name: Coverage
        run: |
          coverage report
